### ISSUE TITLE
[BUG] Missing outer perimeter.

### ISSUE THREAD

**Issue by Mikyner** [prusa3d/Prusa-Firmware-Buddy#3650]
Occasionally, the outer perimeter of a print is missing.
![20231231_213830](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/52259575/8515dd2c-718e-4622-b6e4-11574ac1f5b1)
![20231231_213348](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/52259575/1ae56286-eacd-4477-ba78-5ac1ba88bd0e)

**Comment by MichaelJLew** [comment]
Is the perimeter in the gcode? If not then this is a slicer issue rather than a firmware problem. 

I will note that you have not given any of the information requested by the issue report form. Perhaps you are venting rather than reporting an issue that can be fixed by Prusa...

**Comment by tomoslono** [comment]
I'm having this same issue on PrusaSlicer 2.7.1.

**Comment by the-keybord** [comment]
I have the same issue, it happens random , on different models, different settings, once i saw it happening with my eyes, printer just skipped a few moves of perimeter and then continued printing as normal , 
After that i put the same gcode on print, and issue did not happen,

I contacted prusa , the guy told me there maybe be a faulthy wifi connection or usb drive, but gave me no solution for this

It looks like the printer just skips a few gcode lines and forgets about it

**Comment by the-keybord** [comment]
slicer is good because the same gcode worked the second time, maybe its because i use prusa connect?

**Comment by steinack** [comment]
I have experienced similar problems. Since I disabled "Use ramping lift" in PrusaSlicer, I no longer have any problems. 
![missing_perimeter](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/4296289/f23ee076-0e06-4eab-8867-0a4cea79ecc9)

**Comment by the-keybord** [comment]
I see you had the exact issue i have, but i dont even have "use ramping lift" enabled

**Comment by tomoslono** [comment]
For me the issue resolved after switching from Arachne to Classic generator in Slicer.

**Comment by SmithyAT** [comment]
Had the same issue today twice. Different models, different printers.
I have two MK4 printers and printed a model on the first one and saw a missing outer perimeter about 10mm above the bottom. The perimeter is missing in the whole layer-
Later I printed something else on the other MK4 and had the same issue, but not on the same height, on the second print it was maybe 12mm above the bottom.
It don't happen always. Printed some other things today and they were fine. 
I updated to 2.7.2 yesterday and haven't seen the issue before, so I thought 2.7.2 is maybe causing it. Then found this bug here, so I don't think it is related to 2.7.2.

**Comment by the-keybord** [comment]
do you use usb drive directly or Prusa Connect ?or Prusa Link

**Comment by the-keybord** [comment]
@SmithyAT , provide some info about your settings, are you uploading directly on usb drive, or use wireless? Prusa link or Prusa Connect?

**Comment by SmithyAT** [comment]
I am using Prusa Connect.
Do you think it is related? I always thought that there should be no difference, because the gcode is stored on the use drive anyway.

**Comment by the-keybord** [comment]
@SmithyAT yes, because i use Prusa Connect too,  but some times i used usb drive, and issue never showed, i think there is a probability, we should switch to usb drive and see if this issue ever shows up, 
because i used the same gcode , and first time issue persist and second time no,

**Comment by SmithyAT** [comment]
> @SmithyAT , provide some info about your settings, are you uploading directly on usb drive, or use wireless? Prusa link or Prusa Connect?

I am using default settings in prusa slicer, the model is quite simple, a block with a few cut-outs on the top (it is a holder for some things in the bathroom).
But I've seen your suggestion to turn off ramping lift, and checked my settings, it was enabled, seems to be on per default. Will try to disable it with the next print.

> Do you use upload, or upload and print ?
Both, but as far as I can remember I clicked "upload and print"

But good hint, will try to copy it manually to the usb drive. WIth the wifi speed and the general transfer, everthing could happen :-) Maybe there is no check if the checksum is correct after the transfer. 

But as already said in my initial posting, I've never seen the problem before and I never copied the gcode manually, I am always using PrusaConnect. But it is worth to try it, thanks!

**Comment by the-keybord** [comment]
@SmithyAT i had these issue pretty often , but on very random time, i was using "upload and print" button, but now for a few months i click "upload" and then wait for the file to full upload, and then i click "print" on the printer, and that way issue never showed up, but im just really venting about this nonsense bug , im sorry xd

**Comment by SmithyAT** [comment]
I can understand that, it's annoying.
Will take care next time, how I send the job and will give it a try to just upload it. 
Hope it will be fixed soon, these workarounds needed for PrusaConnect are really annoying, its not the first one, since I used it.

**Comment by hstag** [comment]
I have same issue on my mk4, firmware 6.0.0, Prusa slicer 2.7.4. I am using prusa connect.

**Comment by Koder22** [comment]
I have the same issue with my Mk4 and mini, when using wifi there is a random missing/extra line in the prints.



![IMG_9724](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50591562/796bda8b-e272-45d8-b697-4a0e92b26416)
![IMG_9723](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50591562/abaecbed-81dc-40fc-940c-5ad99ada63d4)
![IMG_9722](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50591562/38a98f6a-6b13-4459-b603-e7778b95e981)

**Comment by Koder22** [comment]
Here is some more examples

![signal-2024-03-01-215046_002](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50591562/42004d98-96df-425f-bf57-010f20ddce87)
![signal-2024-03-02-072235_002](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50591562/44dc46af-4ae1-45c7-96a6-51fd4db8ac29)
![signal-2024-03-07-191327_002](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/50591562/9acb3323-d497-4a20-9bec-8d28fbde73b2)

**Comment by antimix** [comment]
I never experience this, but because I always send the file via PrusaConnect and then I print from the LCD panel.
This can be related to the WiFi BUG that afflicts the MK4 since it was born (see: [ [BUG] Prusa Connect / Link Gcode Corruption on OTA gcode upload #3156 ](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3156)

Do the following:

1. Configure in PrusaSlicer a physical MK4 printer with PrusaConnect.
2. Slice the model in PrusaSlicer and export on your PC.
3. Then upload the same code to the printer using the G button.
4. Wait for the complete transfer.
5. Go on the LCD and exit from the ready to print screen and back to the main menu.
6. Remove the USB key and connect it to the PC
7. Binary Compare the two files if are the same.
   here is a quick and dirty way: 
   - go in windows command line with Start and select Command Prompt
```
   C:\Users\john>fc /b PCobjectName.bgcode D:\MK4objectName.bgcode
   Comparing files PCobjectName.bgcode and D:\MK4objectName.bgcode
**FC: no differences encountered**
```

If you get the "FC: no differences encountered" then the file was not currupted during PrusaConnect transnsfer.
8. Reinstall the USB dongle on the MK4

9. Go on the LCD panel, select the object that you have checked and print it.
10. I suppose that 100% of time it will be perfect. No way to fail.

11. Then go in PrusaConnect, and you should be able to see the same object also there.
12. Print it from PrusaConnect
13. I am not sure if PrusaConnect is just printing the local USB copy or is **resending** the whole file.
14. If it is using the local copy the it should be 100% correct.

15. If you get a bad print with a line, then may be it resent the gcode. In this case after the print, remove the USB. connect it to the PC, and reissue the FC command from dos command. Then the bgcode file should be different.

Let us know.

Regards

**Comment by crasbe** [comment]
@antimix I experienced issues with my new Mk4 as well. In particular, at a certain height it moved veeeeeeeeeery slowly (barely noticeable). But it recovered after I paused the print (which took forever as well, probably 5 minutes or more).
Unfortunately I did not follow your guideline because I only researched the issue after it happened.

The printer has the latest 6.0.4 firmware.

This is what I know:
- The file was transfered to the Mk4 via PrusaConnect from PrusaSlicer 2.8.0 and started directly. The issue occured at a height of 16.65mm on a move without extrusion and continued during the next movements with extrusion.

- It seems to have recovered after pausing the print, but the pause took very long to be in effect.

- After the print finished (well, it failed, because the part came off the bed. Not sure if that's related or not.), I downloaded the .bgcode file and it is 100% identical with a file that was saved locally.

- Then I disabled PrusaConnect and PrusaLink (I did not use PrusaLink, it was just enabled) and restarted the same file and it did not have the same issue. However the printer was powercycled in between.

- Previously I had issues with incomplete outer perimeters as well, which seems to be gone now too.

- The issue has been present in two different WiFi networks in two different parts of Germany with different internet connection speeds (50MBit and 16MBit). Both routers are Fritz!Box routers, however different types.

**Comment by michael-kobb** [comment]
I had this issue the other day on one of my first prints from Prusa Connect to my MK4. The printer simply skipped some of the gcode on the top layer, leaving a sort of diagonal stripe of missing material. I sent the print directly from Prusa Slicer 2.8.0 to my MK4 which is running 6.0.4+14924.

I downloaded the gcode from the printer and exported it from the slicer. Comparing the two files using the diff utility on the Mac, they are identical.

![IMG_3561](https://github.com/user-attachments/assets/7daabc66-bf88-4e18-8159-877c96d91d15)
![IMG_3560](https://github.com/user-attachments/assets/a1ab9471-84a6-438d-972a-57f2f19482d8)

**Comment by michael-kobb** [comment]
Phooey. Happened again, this time on my XL. Apologies for the quality of the photo. I snapped the pic while it was still printing and it was ASA so the enclosure was closed. This was on my XL 5T running 6.1.2.
![IMG_3609](https://github.com/user-attachments/assets/36129f9b-f172-4dd8-870b-5b27981e3ae0)

**Comment by Dorito203** [comment]
I have the same problem (Firmware 6.1.2+7894) and the frequency has increased in the last few weeks.
I now have this issue in almost every print, in the beginning it only occurred quite rarely.
I transfer the files via Prusa Connect and usually start the print from the display.

**Comment by Koder22** [comment]
> I had this issue the other day on one of my first prints from Prusa Connect to my MK4. The printer simply skipped some of the gcode on the top layer, leaving a sort of diagonal stripe of missing material. I sent the print directly from Prusa Slicer 2.8.0 to my MK4 which is running 6.0.4+14924.
> 
> I downloaded the gcode from the printer and exported it from the slicer. Comparing the two files using the diff utility on the Mac, they are identical. And of course if I look at the gcode file with the gcode viewer utility in PrusaSlicer, it does not show any part missing.
> 
> ![IMG_3561](https://private-user-images.githubusercontent.com/180352937/364169873-7daabc66-bf88-4e18-8159-877c96d91d15.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MjMwMzAsIm5iZiI6MTcyNTcyMjczMCwicGF0aCI6Ii8xODAzNTI5MzcvMzY0MTY5ODczLTdkYWFiYzY2LWJmODgtNGUxOC04MTU5LTg3N2M5NmQ5MWQxNS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDdUMTUyNTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzhhM2RlOWZhMDcyY2QyNmMwMDg2ZmQ5M2Q2MjhiYzgwM2QxNzU0Mzg5MWU0YzQ5YzY0YzIwYmFjZmJjYmNjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ED7bgCI1FCbZGBnYL_E2lo_U2YJ7U9m5qamLSxCwOZ0) ![IMG_3560](https://private-user-images.githubusercontent.com/180352937/364169875-a1ab9471-84a6-438d-972a-57f2f19482d8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MjMwMzAsIm5iZiI6MTcyNTcyMjczMCwicGF0aCI6Ii8xODAzNTI5MzcvMzY0MTY5ODc1LWExYWI5NDcxLTg0YTYtNDM4ZC05NzJhLTU3ZjJmMTk0ODJkOC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDdUMTUyNTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWI0NWMwNTJjZWYzNTZkNTk2OThiYWFjOTYxY2IzNDk2ZTY0NDYyNTVmZGVhM2VjNGEzYTY3OWMwYzEyYWJjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FvFfof3b1dRoqHOSdVLTMI8vYYSzS-lbPAvpAo0ADXI)

I have had this happen also, a couple of times. Did the same comparison test and found that g-code was identical.

**Comment by WeaselWasher** [comment]
Ugh.

Me too.
I also had the XL USB drive disconnected issue. 
Wonder if it's related. 
I sent all of it off to prusa for analysis.
![PXL_20240920_145707088.jpg](https://github.com/user-attachments/assets/88569446-5dab-4527-a9d3-1b1035cff72d)

![PXL_20240920_145718833.jpg](https://github.com/user-attachments/assets/bbb9f420-54ba-45bc-869c-25c2bd020932)

![PXL_20240920_000630102.jpg](https://github.com/user-attachments/assets/2b3f7dfc-3192-4181-9c47-98739670426d)


I also had one support on the red print fall over - not sure why - but it's like that one layer just didn't fully print and it fell over.

These are two different iterations on two different versions of firmware and the red one is also sliced with the newest prusa slicer released two days ago.
I transferred the file directly to the USB from my computer. I have prusalink and connect disabled on my XL, though - wifi is still enabled.

**Comment by CZDanol** [comment]
@WeaselWasher 
> These are two different iterations on two different versions of firmware (XL 6.1.2 and 6.2.0 alpha) and the red one is also sliced with the newest prusa slicer released two days ago, where the black was the previous version.

I don't understand what you meant by this.

Also, yes, guys, if you are having skipped gcode issues like what I see on the photos from @michael-kobb, please try out 6.2.0, should be fixed there: https://github.com/prusa3d/Prusa-Firmware-Buddy/releases

**Comment by WeaselWasher** [comment]
@CZDanol 

By different iterations, I mean that it was the same model, repeated.  

The black print was done in 6.1.2 and the red was done 6.2.

**Comment by CZDanol** [comment]
So, you had a USB disconnected issue on 6.2.0?

**Comment by WeaselWasher** [comment]
> So, you had a USB disconnected issue on 6.2.0?

I had no fault, but I did have the missing perimeter (this is a thread for missing perimeters) is this the same problem as the USB disconnected issue? 


I have a different petg print going right now that's been going for 12h so far, in two colours. But I haven't noticed any issues yet. It's only half done though. I won't be able to fully inspect it until it's done, but so far no USB disconnect faults or visible missing perimeters

**Comment by WeaselWasher** [comment]
@CZDanol 

Yes. It appears I am still getting the missing perimeters in today's print with 6.2
![PXL_20240922_174125129.jpg](https://github.com/user-attachments/assets/7821d76a-0ea9-4f19-9592-a409a34d7f36)

It's a little hard to see - as it's translucent. But you can definitely see the blob

**Comment by hstag** [comment]
Firmware 6.1.3 issue still persist.
![20240922_192848.jpg](https://github.com/user-attachments/assets/91db7941-77b8-4db7-939f-7327b0063c5c)

**Comment by michael-kobb** [comment]
> Also, yes, guys, if you are having skipped gcode issues like what I see on the photos from @michael-kobb, please try out 6.2.0, should be fixed there: https://github.com/prusa3d/Prusa-Firmware-Buddy/releases

I'd like to be sure that I understand what 6.2.0 contains. Do you believe that the missing perimeter issue that is described here is related to the USB disconnection issue? I have had the missing perimeters happen when using Prusa Connect (never when Prusa Connect is disabled). I have only ever had the USB disconnect problem occur when trying to start a print, never during the print.

If 6.2 is supposed to resolve the missing perimeter issue, I will install it and give it a try, but it will probably be next week before I can do so due to other commitments.

**Comment by CZDanol** [comment]
I'm not convinced these missing perimeters are related to the USB - so we're not expecting the perimeters to be solved (it would be very nice though). We have however found out something somewhat related to connect and fixed it, so maybe things could get better as well.

Got an idea - do you have Touch Sig Workaround enabled by any chance?

**Comment by michael-kobb** [comment]
> Got an idea - do you have Touch Sig Workaround enabled by any chance?

I do not have that enabled. (I had to google it to find out what it is!) My touch screen seems to work fine.

I agree it would be very nice if this were fixed, but it's a little worrying that this issue, which is now nine months old, does not seem to be under more urgent investigation. It renders Connect unusable on both of my printers.

**Comment by michael-kobb** [comment]
Connect doesn't work through wi-fi?? Man, I'm so glad you said that. I was just about to update the printer, but that would have done me no good at all. I don't have Ethernet at that location.

**Comment by WeaselWasher** [comment]
Yeah. I'm not sure what happened. It's reported already by others. It just denies the connection. Could be a troubleshooting step on purpose. It is alpha after all. I strapped mine in with Ethernet somewhat temporarily. Wanted to try using connect again since danol said they found and fixed an issue with it. 
I also just replaced my ribbon cable with a double shielded cable, with the shield grounded on the main board side. I've got another 15h run going. So I guess we'll see how my perimeters look tomorrow.

**Comment by michael-kobb** [comment]
Good luck! I don't have Ethernet where the printers are, so it would be a challenge to try out 6.2 with Connect. Maybe that will be fixed before I get back from my travels.

**Comment by WeaselWasher** [comment]
> I also just replaced my ribbon cable with a double shielded cable, with the shield grounded on the main board side. I've got another 15h run going. So I guess we'll see how my perimeters look tomorrow.
> 

Well. It finished, and I can't see any missed perimeters on this one. 
![PXL_20240925_001156745.jpg](https://github.com/user-attachments/assets/a11b28a5-7e87-4763-9883-28b5296d8e71)

**Comment by crasbe** [comment]
> Also, yes, guys, if you are having skipped gcode issues like what I see on the photos from @michael-kobb, please try out 6.2.0, should be fixed there: https://github.com/prusa3d/Prusa-Firmware-Buddy/releases

So far I printed for about 30 hours on the XL with Prusa Connect via Ethernet and no perimeter (or other) issues arose. However I never tried it on this XL with Prusa Connect before after the issues with the MK4.
I have yet to try it on my MK4 with WiFi, which previously had the perimeter issues.

**Comment by Koder22** [comment]
I did the following on my MK4(factory built, no mods), printed 6 benchys with Prusa Connect(half with "upload and print" and the other half with "upload" and then pushed print on the printer. Result: 3 of the 6 benchys had missing perimeters at the height of 15-20mm.

Then i printed 6 benchys using Prusa Link, and all came out nicely without any missing perimeters.

I cant find any difference between the file thats transfered to the printer, and the one on the computer with the slicer. The missing lines doesnt appear on the same place with the same GCODE. 

![image](https://github.com/user-attachments/assets/a14d42b5-8d62-497b-a311-fb8478e33b70)

**Comment by CZDanol** [comment]
@Koder22 that was a very nice engineering approach. Thank you for that :)

Just to clarify some things:
- Those 3 out of 6 benchies, I assume those were the benchies that you printed using "upload and print"?
- What was the version of the firmware you were trying this on?

**Comment by Koder22** [comment]
I printed 3 benchys with "upload and print", two of these had missing perimeters. Then i printed 3 benchys with "upload" and then "print" on the printer, one of these had missing perimeters. I have Prusa 6.1.3 on my printer, i have had these issues since december 2023 when i got the printer.

**Comment by Koder22** [comment]
The upper Benchy is printed with Prusa Connect, but didnt have any missing perimeters. The lower one is printed with USB transfer. There is a lot of small defects in the upper one, and these are also present on ones printed with Prusalink.



![image](https://github.com/user-attachments/assets/daf34692-285d-4ac2-afac-cf939a22d7fd)

**Comment by the-keybord** [comment]
@Koder22 Thanks for your investigation
I also want to clarify something:
The prints when you hit "upload" and then "print" , did you wait for the file to load 100%? or you just click print the same moment it displayed on the printer?

My way to avoid this issue is i hit "upload" , then i wait for the whole file to load to printer, and then I click print, 
for a couple of months of using this technique i never had issues with skipped gcode or perimeters

Thanks

**Comment by crasbe** [comment]
> > Also, yes, guys, if you are having skipped gcode issues like what I see on the photos from michael-kobb, please try out 6.2.0, should be fixed there: https://github.com/prusa3d/Prusa-Firmware-Buddy/releases
> 
> So far I printed for about 30 hours on the XL with Prusa Connect via Ethernet and no perimeter (or other) issues arose. However I never tried it on this XL with Prusa Connect before after the issues with the MK4. I have yet to try it on my MK4 with WiFi, which previously had the perimeter issues.

So far the MK4 printed close to 20 hours without a single issue, always using Prusa Connect to upload the file and immediately start the print afterwards. The XL has not shown any perimeter issues either after another 20 or so hours.

<hr/>

@Koder22 I don't think this is an EMC issue, considering 6.2.0-alpha1 fixes the issue for me.

From a physical standpoint, the stepper cables have a much higher potential to radiate EM fields than to be affected by EM fields. WiFi works in the Milliwatt range while the steppers are driven with much more power (that's why they get warm).
Apart from that both work in different frequency ranges, and a big electromechanical device such as a stepper wouldn't show much to any response to high frequency signals such as WiFi.

The stepper control is open loop, so there is no feedback from the stepper to the controller that could somehow be affected either.

**Comment by Racemade** [comment]
Have the same issue on my XL. One outer perimeter is missing.![image](https://github.com/user-attachments/assets/5adb3c40-19ba-4172-bdc7-5c047856cd03)

**Comment by michael-kobb** [comment]
Was that printed from Connect?

**Comment by Racemade** [comment]
Directly over the slicer

**Comment by Koder22** [comment]
I installed newest firmware on my MK4, 6.2.0 Alpha 1, and did a testprint. This actually looks really good, it has no dimples/artefacts, and no missing lines. I will print a few more just to be on the safe side, but im hoping that this firmware fixed the error!

![image](https://github.com/user-attachments/assets/69cac3cb-cf90-4c63-8644-af56c09632e2)

**Comment by Racemade** [comment]
Another idea:
Could the slicer option "arch firting" (enabled g2/g3) coase the  problem? I remember that ive checked the box a few days before...before it was unchecked.

**Comment by MichaelJLew** [comment]
Enabling G2 and G3 may cause a problem. I previously had a bug report here on G2 and G3 curves having blobs because of short pauses during their execution. That report timed out and has been removed, I think, but the problem seems to have persisted. I have very few arcs (G2 and G3) commands in my print files nowadays as a workaround for the original problem, but I do heat minor stuttering of my MK4 where they are used.

**Comment by Racemade** [comment]
Thank you for your comment. I will uncheck the box again. Hoping for 6.2 that the issue may resolved for prusa connect.

**Comment by michael-kobb** [comment]
I've been using my XL for the past week with the 6.2 alpha 1 firmware. This release breaks Wi-Fi, annoyingly, so I've been using Ethernet, but I have not seen the missing perimeter issue during this time.

Now Prusa has released 6.2 alpha 2, which fixes the Wi-Fi breakage. But it seems that all they've done for that fix is to revert the prior change, so I fear that it will reintroduce the missing perimeter bug.

**Comment by helder112** [comment]
Hello All,
I would like to ask if any  bug correction was done on this matter. I also have this issue on my mk3.5 printer.

![IMG_20241124_201821](https://github.com/user-attachments/assets/6b9b1860-56b6-4022-ba14-e5222f61d122)

**Comment by michael-kobb** [comment]
I've held off updating to 6.2 alpha 2 out of concern that it will bring the perimeter issue back if Prusa Connect is enabled. I was planning that I would maybe update to alpha 3 or whatever came next, but so far there have been no further updates.

I'm very disappointed in how slowly Prusa seems to be moving to address this issue.

**Comment by crasbe** [comment]
The Alpha 2 did not bring the perimeter issue back. I've been printing with it for weeks with dozens of days of printing days now.

**Comment by Racemade** [comment]
Jep, works fine! :)

**Comment by WeaselWasher** [comment]
I'm also using prusa connect via Ethernet on alpha 1 (haven't bothered with
alpha 2 since I'm hardwired) no issues

**Comment by michael-kobb** [comment]
That's encouraging, thanks. I'll update to alpha 2 and give it a try.

**Comment by Koder22** [comment]
Alpha 2 works on my MK4, no missing perimeters. I also feel that Prusa could have done a lot better on this, i spent much time trying to fix my MK4 since i got it a year ago, and there is still not a working firmware(only a alpha).

**Comment by Prusa-Support** [comment]
The firmware release [6.2.0-alpha1](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.2.0-alpha1) includes overhauled USB media prefetch feature, which should drastically reduce the chance of "clogged buffer" hence "skipped lines/layers" or "frozen print".
A later firmware release [6.2.0-alpha2](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.2.0-alpha2) proved to be a pretty stable firmware over a significant amount of testing hours, providing an effective correction of this erratic bug.
You can rely on the latest alpha release while the final firmware 6.2.0 with a few additional adjustments should follow in short.
 
Michele Moramarco
Prusa Research

**Comment by michael-kobb** [comment]
Thank you. I'm flashing now and hoping that this will be a good solution.
