### ISSUE TITLE
[BFW-5647] [BFW-6752] [BUG] Wrong Z after Spooljoin

### ISSUE THREAD

**Issue by firetech** [prusa3d/Prusa-Firmware-Buddy#4030]
**Printer type** - MK4, with MMU3

**Printer firmware version** - 6.0.1+14848

**Original or Custom firmware** - Original

**USB drive or USB/Octoprint** -  USB drive

**Describe the bug**
I've had it happen twice now (also the amount of times I've used Spooljoin on this printer) that the printer doesn't seem to return to the correct Z height after doing the Spooljoin filament switch for the rest of that layer. The next layer after it looks fine, though. The first time, the rest of the layer just looked slightly off, the second time, the filament barely stuck on for the rest of the layer. It looks like bridging, but it was supposed to be the last layer of solid infill...

![2024-06-05 10 09 13](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/104522/6245a6a8-72ce-4c69-834b-2fe6a713e8c7)

Note that the first layer of grid infill looks fine next to the problem area, so the next layer was unaffected. Also, the grid infill that can be seen in the problem area is _on top_ of what's supposed to just be solid infill. It may look like it's just bridging over the grid infill, but that isn't the case.

I've manually paused this printer multiple times without issue, it's just Spooljoin that has shown this behavior.

**How to reproduce**
Start a print with Spooljoin, make the filament run out mid-layer.

**Expected behavior**
The rest of the layer after a Spooljoin filament switch should look the same as before the filament was switched.

**Comment by danopernis** [comment]
Thanks for the report @firetech it is always great when bugs are reproducible :slightly_smiling_face: I have created internal ticket BFW-5647

**Comment by jmillerfo** [comment]
I have the same problem.  I was hoping this would be fixed in version 6.0.4 but it was not or at least not reported in the change log.

**Comment by firetech** [comment]
I retested this yesterday with 6.1.4+7908 on a MK4S, and the printer returned to the correct Z after an induced spool join during the first layer (0.2 mm). Thinking this issue was fixed, I started a print with spool join configured, and when the filament ran out at layer height 1.2 mm, the printer did a spool join and promptly returned to printing ...at layer height 1.45 mm. 😞

Skimming the code related to spool join, I can't find anything obviously wrong (although, I'm admittedly not exactly familiar with this code base).  Some thoughts:
* Could it be other threads modifying the `current_position` and/or `destination` variables?
  * Side note: Is the value set to `destination` [here](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/8978fe1b166806a4ef6ecc5bff210cbbf183fc06/lib/Marlin/Marlin/src/module/prusa/spool_join.cpp#L259) ever used with MMU spool join? `MMU2::mmu2.tool_change_full()` stores its own return position [here](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/8978fe1b166806a4ef6ecc5bff210cbbf183fc06/lib/Marlin/Marlin/src/feature/prusa/MMU2/mmu2_mk4.cpp#L665).
* Could this be affected at all by having the "Z height" footer enabled? (I'll probably test this myself later when my printer isn't busy printing.)

**Comment by CZDanol** [comment]
Hello, this should be fixed now in 6.2.0-alpha2. Can you please retest on that version?

**Comment by firetech** [comment]
Ah, I didn't see any mention of that in the changelog. I'll test it out!

**Comment by CZDanol** [comment]
Great :) Closing the issue, will reopen if we find out there is still something to fix

**Comment by FlowerDIY** [comment]
Hi Danol,

I have encountered this issue on 6.2.0 alpha 2. I have ruled out calibration issues because multi color prints come out flawlessly. I only see the wrong Z offset when spool join occurs at filament runout. 

Would you suggest re-loading the firmware to see if that fixes it?

**Comment by FlowerDIY** [comment]
I have been getting this issue in 6.2.0 alpha 2.
Multi color prints come out fine, so I can rule out calibration.
When I do a spool join, the z offset is apparently zero from the previous layer causing the tool to be directly in contact with the previous layer and ooze filament out of the side.
The z is correct after that, and the rest of the print comes out fine. I can reproduce this with every print by cutting the filament and letting it run out.

**Comment by CATSNACKz** [comment]
I'm on 6.2.0 and this is still an issue. After spool join, it prints a little too high, but will fix itself once it moves to a new layer or moves the bed so it can move to a new spot on the current layer. This is only an issue with spool join. This does not happen in multi color/material tool changes. In my photos you can see it printed good until it did spool join and started printing too high. Then when it moved to another spot on the bed, it went back to printing good. 

![Image](https://github.com/user-attachments/assets/0bc59a92-b59b-4410-98a0-c7d5ca380ef2)
![Image](https://github.com/user-attachments/assets/2ed5cda1-0735-4564-99f0-301f24cba34b)
![Image](https://github.com/user-attachments/assets/1ef45c86-1199-4d46-9378-7be85c3da57e)

**Comment by CZDanol** [comment]
Reopening and assigning a new ticket: BFW-6752 (formerly BFW-5647)

**Comment by firetech** [comment]
Should this issue be fixed by 6.2.3, or is the fix quoted below a separate issue? 🤔 

> Fixed returning to wrong Z position after pause
> When unpausing, the printer was not applying the MBL correction to the unpark move.

**Comment by FlowerDIY** [comment]
![Image](https://github.com/user-attachments/assets/f178cef5-c31a-49b1-b081-d86bfb70418b)

Tested in 6.2.4 RC1, and it still returns to the Z height after spool join.

The new firmware addresses the wrong Z position after a pause, but this does not appear to fix the spool join issue. 

The important part is that normal multicolor prints turn out fine. If there is any other troubleshooting I can do to more thoroughly test this issue, please advise.

**Comment by CZDanol** [comment]
Hello, testing wasn't able to reproduce this issue on our 6.4 branch, so we are thinking that it got fixed somewhere along the way. Our current plan is to wait for the 6.4 release, and potentially revisit this issue if we get new reports.

**Comment by 3d-gussner** [comment]
Please verify if [Firmware 6.4.0-alpha](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.4.0-alpha) solves the issue.

**Comment by FlowerDIY** [comment]
It looks like it may nearly be solved, but something else seems to be
broken with spool join sequence.
The main head crashes into the dock when docking, and the print results in
a large layer shift in X. The Z height appears to be correct though.

Tools 4 is main and 5 is the join head.
Start print (36mm cube)
At about halfway through the print, run out of filament on tool 4.
Tool 4 move to dock and waits for temperature on tool 5.
Tool 5 reaches temperature
Tool 4 attempts to dock and results in erratic motion, violently jumping
and crashing into the dock, but ultimately docks with no error or fault.
Empty carriage does homing routine
Carriage picks tool 5 successfully and resumes print
Print continues with shift in X axis by 2-3mm mm. But Z is the correct
height.

This occurred repeatably in 3 attempts.

**Comment by 3d-gussner** [comment]
@FlowerDIY Thanks for testing 6.4.0-alpha. Glad to hear that the Z height is now correct.
There have been multiple reports that the alpha causes some issues on XL with the tools. There is another ticket you can comment on.

**Comment by CATSNACKz** [comment]
I'm on FW 6.4.0 and I don't think this is fixed yet. Once spool join happened, it looks like the z height wasn't right because the line it printed came loose and drifted over to another object. This caused a layer separation on both objects. It printed just fine after this, presumably after z-hopping once. 

![Image](https://github.com/user-attachments/assets/537e423e-3c9f-4a6e-a775-3687aecc624a)

![Image](https://github.com/user-attachments/assets/46b835e2-9682-429b-8338-4176eefa3b71)

![Image](https://github.com/user-attachments/assets/1e463c41-d9bc-44b6-84f6-e551643f869b)

**Comment by 3d-gussner** [comment]
@CATSNACKz Can you give bit more information?
MK4S FW 6.4.0 + MMU3 FW 3.0.3?

This Z height issue only happens during Spool Join, or also when you runout of filament and reload filament?

**Comment by CATSNACKz** [comment]
This is on the XL. Multi color prints are good. This only happens during spool join. I have not tested reloading the same toolhead.

**Comment by FlowerDIY** [comment]
I have the same issue on XL5T in FW 6.4.0.

Testing with 6.2.6 gave me 3 successful spool joins. I am going to test a few more times to confirm.

Edit: tested again in 6.2.6 and got the wrong z height after spool join again. It only appears to be wrong for a portion of the layer then the next layer is correct.

**Comment by crasbe** [comment]
It seems that the issues in #4963, #4985, #5054 and #5058 are pretty much the same as this issue here. However this issue already has tickets for the internal Prusa issue tracker attached.

To avoid opening more issues for the same underlying bug, I want to add a reproducible example here. The bug can be triggered by changing the filament in a currently not-active tool as well.

<hr/>

I created a simple cube with two colors in PrusaSlicer and manually modified the G-Code to include an `M600 T1` command to change the filament in the non-active tool T1 *before* T1 is used for the first time. You could also do that in the menu, I think Firmware 6.4.0 added a feature to change the filament in the non-active tool.

Attached you can find the .3MF file with the PrusaSlicer project and the manually modified G-Code. The cube is sliced for Prusament PLA on a Prusa XL 5T, but it would be reproducible with a Prusa XL 2T machine as well.

<img width="508" height="748" alt="Image" src="https://github.com/user-attachments/assets/0db45e19-1caa-4308-b041-970c9b5e1e5e" />

<img width="862" height="623" alt="Image" src="https://github.com/user-attachments/assets/04d78ba2-e32c-4993-96dc-190beaa306d6" />

The resulting cube clearly has an incorrect layer height after the filament change. Also, the tool head does a nozzle-touch homing, which is less than ideal if there's already something big on the build plate 👀 

<img width="1700" height="956" alt="Image" src="https://github.com/user-attachments/assets/a3bb7518-36ce-4150-8849-3495b2a96302" />

[Form-Kubus_0.4n_0.25mm_PLA,PLA_XLIS_18m.gcode.zip](https://github.com/user-attachments/files/24643517/Form-Kubus_0.4n_0.25mm_PLA.PLA_XLIS_18m.gcode.zip)

[Form-Kubus.3mf.zip](https://github.com/user-attachments/files/24643529/Form-Kubus.3mf.zip)

**Comment by crasbe** [comment]
The aforementioned behavior is also documented in #5040.

**Comment by crasbe** [comment]
Possibly #5027 is also related to this.

**Comment by taco-taco-taco** [comment]
I just saw this on a 5T with 6.4.0 glad I saw this before I started looking for mechanical issues....

**Comment by crasbe** [comment]
It would be nice to get a confirmation if this issue was solved with 6.4.1 before closing it.

**Comment by crasbe** [comment]
Not stale.

**Comment by FlowerDIY** [comment]
This is still a major issue for me. This results in added labor or lots of wasted filament when the spool join would otherwise be used. This was a major selling point of the XL but does not work correctly.On Jul 27, 2026, at 10:07 AM, crasbe ***@***.***> wrote:﻿crasbe left a comment (prusa3d/Prusa-Firmware-Buddy#4030)
Not stale.
