### ISSUE TITLE
[BUG] Opening doors causes crash

### ISSUE THREAD

**Issue by greggjaskiewicz** [prusa3d/Prusa-Firmware-Buddy#4469]
### Printer model

CoreOne

### Firmware version

6.3.0 

### Upgrades and modifications

Noe

### Printing from...

USB Drive 

### Describe the bug

Opening doors at some points causes either crash (probably triggering watch-dog, the way it behaves). 
I found this happening either during initial warm up/bed mesh, or during final descent when print is done - and I'm eager to open the door! 

Or on other occasions (probably should be separate bug) - throws UI dialog in the middle of another event. Picture running out of filament, and being prompted to confirm that correct colour has been observed. I want to then open the door and pinch away the excess - but dialog on the screen obstructs the new-filament query dialog. It's almost like door opening event has just been a last minute slap on top of the firmware. 

### How to reproduce

run print, and open the door either before print starts properly or when it finishes and bed descends down Z - to lower position. 

### Expected behavior

Opening the door shouldn't cause everything to crash or other higher priority (such as filament reload) dialogs should not give way to it. 

https://github.com/user-attachments/assets/088b0164-5d0d-4bc1-9eb1-359b4faf47ee

**Comment by CZDanol** [comment]
Hello, thank you for reporting. The printer restart at the end should be fixed in 6.3.1. The one at the beginning will probably take a bit longer. Internal ticket: BFW-6705

**Comment by thijstriemstra** [comment]
nobody at prusa thought about ever testing something so obvious blows my mind. lots of these gems in bug tracker.

**Comment by danopernis** [comment]
@greggjaskiewicz 6.3.1 was just released and contains fixes to the issues you were having.

@thijstriemstra thank you for your valuable insights.

**Comment by Avarios** [comment]
@danopernis Printer still crashes when you open the door during print (Before that only when you opened the door when the Pause macro was still running)

**Comment by MCraft555** [comment]
I got a similar issue that the firmware crashes when opening the door after pressing retry for the bed leveling. Firmware version 6.8.1+16182.
