### ISSUE TITLE
[BUG] Core One DIY or advanced filtration does not work with Octoprint

### ISSUE THREAD

**Issue by BlueFyre** [prusa3d/Prusa-Firmware-Buddy#4690]
### Printer model

Core One

### Firmware version

6.3.3

### Upgrades and modifications

None

### Printing from...

Octoprint

### Describe the bug

Filtration does not happen during or after a print when using ABS with Octoprint

### How to reproduce

1. Set the filtration system to DIY filtration or advanced
2. Load a filament which has the requires filtration
3. Start a print via Octoprint

### Expected behavior

Chamber filtration should happen during the print
Post-print filtration should also occur

### Files

Project and gcode: [calicat v2.zip](https://github.com/user-attachments/files/20764397/calicat.v2.zip)

**Comment by BlueFyre** [comment]
I just tested printing files off of the USB stick and it works as expected so it's in particular to serial printing

**Comment by Silvenga** [comment]
I'm using the Advanced Filtration addon and I am also seeing the fan not running during serial printing.

**Comment by BlueFyre** [comment]
Thanks, I've edited the title and description

**Comment by Silvenga** [comment]
I contacted Prusa support... the first answer I got back was I needed to check the ambient environment temperature, because they claim the _filtration fan_ only runs if an ambient temperature is set in PrusaSlicer (which would make absolutely no sense).

So I'm not confident in getting an actual solution...

**Comment by Silvenga** [comment]
@CZDanol sorry to ping you, but Prusa support is dodging my questions over the past week. So far I've gotten:

> Michael Kuznetsov - The filtration fan is controlled automatically based on the ambient temperature set in PrusaSlicer for your project. 

And when asked if there's G-Code support to workaround this issue, I got:

> Michael Kuznetsov - You should be able to adjust just the speed if the filtration fan in the Control menu in the printer's menu. 

- Do the filtration fans not work with serial? (which goes against the marketing of it being firmware controlled)
- Is there any G-Code to control the filtration fans if filtration doesn't work with serial (which I'm guessing is the case, given the firmware might not know when the print actually ends)?

**Comment by BlueFyre** [comment]
@Silvenga I took a [look at the code](https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/f61edb3981c22ffda612c6ff390c3cc7804cd01e/lib/Marlin/Marlin/src/gcode/temperature/M106_M107.cpp#L98) and it seems that you should be able to do it with `M106 P3 S255` to turn the chamber fan to max speed (speed is 0-255; so 102 for 40%)

You'd also need to disable the output of M191 and M141 in the start gcode since you're controlling it manually
I think it should be possible to also have it mimic the "auto" behavior on the printer using M106 in your profile though there's no "needs filtration" flag in the slicer to rely on to know when to activate "chamber filtration" (assuming you don't want to just hard code some stuff). Also the post-print filtration feature would then need to also be included in your end gcode as appropriate

I haven't tested this yet but let me know if you give it a shot. I agree that ideally this should just work the same as printing a file from USB. I wonder if there perhaps needs to be some kind of start/end signal outputted from the slicer as appropriate (since you can send manual gcode from the console and the printer thinks it's "printing")

[Edited to add]
Forgot to add, to be clear the chamber nominal temperature value set in the slicer seems to be working appropriately. It's the "needs filtration" that doesn't appear to be taken into account during serial printing

**Comment by Silvenga** [comment]
Ah, thanks! I was trying to track the code from the top down, and got stuck. You're correct, `M106` does control the filtration fan (index `4`).

```
M106 S255 P4 ; Filtration 100%
```

I've been testing the auto flag, and can't figure out how it works from the code since it seems controlled by the external board (?). In my testing it appears to just turn off the fan.

But related, I did see `M865`, which via `F` sets filtration required. In theory, this doesn't matter, given the filament is configured to require filtration in firmware - but I'll test with it anyway.

This will be enough at least to automate this process. I'm guessing it would be best to always set the fan back to auto after taking control of it.

---

And aside, whoa, this code is wonky (to be clear, not blaming anyone). I can see why features are hard to develop.

**Comment by BlueFyre** [comment]
Oh I see, index 4 is the filtration fan. I was using the DIY one so I pointed to the chamber fans but good to know you can at least control yours too

I think M865 just sets the parameters of the filament profile on the printer itself, but if you set that appropriately on the printer (and used it while loading), then it should already be as expected

As for setting things back to auto, definitely couldn't hurt to reset the value instead of just setting it to 0

**Comment by BlueFyre** [comment]
Not stale

**Comment by BlueFyre** [comment]
Not stale

**Comment by Prusa-Support** [comment]
Should this be considered a duplicate of #4479? 
Maybe the other way around, considering that issue #4479 is theoretically solved by #4484 but not necessarily specific to Octoprint.
Your opinions would be more than welcome.

Closing closely related or duplicated issues may improve tracking of specific requests.

Michele Moramarco
Prusa Research

**Comment by Silvenga** [comment]
Unrelated to those two issues, but this issue does appear fixed in the latest RC. I'm seeing filtration run in serial mode. 

I'll let @BlueFyre comment on DIY filter handling though.

**Comment by BlueFyre** [comment]
It's unrelated to the actual temperature reporting. It just has to do with the filtration system itself. I haven't tested it in the latest build but good to hear that it's possibly fixed by it

**Comment by mvadu** [comment]
I think this is more of a related to #4480 which was marked fixed with 6.4. Given the ask here this can also be marked as closed.

**Comment by Silvenga** [comment]
> I think this is more of a related to [#4480](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/4480) which was marked fixed with 6.4. Given the ask here this can also be marked as closed.

Different issue @mvadu. The issue here is that the filtration fan wouldn't automatically turn on regardless of filament type, but only when printed in serial mode. So even when printing with a filament that was set to need filtration, filtration never activated.

As mentioned, I can confirm this was fixed for at least advance filtration - but the DYI filtration was a different code path, IIRC.

**Comment by BlueFyre** [comment]
Not stale. Haven't had time to test it though

**Comment by bkerler** [comment]
Be aware that there is a bug in the latest firmware for the filtration not turning on if PLA/PETG etc. is being used, I already wrote a PR for that. But for ABS etc. it should be fine.

**Comment by AverageJoe89** [comment]
For DIY filtration bug is still there, on Core One L, FW 6.5.3+12780, for ASA.

**Comment by AverageJoe89** [comment]
Still present.

**Comment by AverageJoe89** [comment]
Can be related to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/4691

**Comment by zzqzzqzzq** [comment]
Not stale. -- Shoo fly'....
