### ISSUE TITLE
[BUG] XL: Frequent Dock Collisions Since Firmware 6.4.0-alpha

### ISSUE THREAD

**Issue by metikumi** [prusa3d/Prusa-Firmware-Buddy#4876]
### Printer model

XL 5-Tool

### Firmware version

6.4.0-alpha

### Upgrades and modifications

None

### Printing from...

Prusa Connect

### Describe the bug

Since updating to firmware 6.4.0-alpha, my Prusa XL frequently crashes when docking the toolhead at the end of a print. The issue occurs during the final move back to the dock, right after a print finishes.

The toolhead approaches the dock diagonally across the print bed, but at pin height it continues this diagonal movement. This causes the docking pins to collide with the two metal latches on the toolhead, resulting in a docking crash.

This happens in roughly 1 out of 6 prints, seemingly at random.

Additional Information:
- Recalibrating the dock position did not solve the issue.
- I experienced this behavior sporadically with the original firmware, but it was fixed in an early update. With 6.4.0-alpha, the issue has returned and occurs more frequently.

### How to reproduce

I cannot reproduce it reliably, but it happens more often when the print ends on the front left side of the printer bed and it's a dock on the right side (diagonal movement).

**Comment by 3d-gussner** [comment]
@metikumi Thanks for testing the alpha firmware. There is already some github issues reported that. The developers are working on that.

**Comment by RuudGosens** [comment]
In my case, the tool head crash happens after changing filament. It doesn't matter which tool head I use. They all crash after a filament change.
The filament change itself goes smoothly. After the change, the tool head also parks normally.
But as soon as the tool head is used during a new print after the filament change, it crashes while docking after the first layer is finished  by the tool head.
The tool head is then a few millimeters too far to the right on the x-axis.
Re-calibrating the tool head is pointless. After another filament change, the same thing happens again.
The only solution for me is to perform a home calibration after changing the filament in a tool head.

**Comment by FluxSnake** [comment]
I have the same issue. I rolled back to 6.2.6 firmware and tested it.

**Comment by 3d-gussner** [comment]
@RuudGosens @FluxSnake Also thanks for testing the alpha firmware.

**Comment by dav991** [comment]
I have experienced the same issue with the 6.4.0-alpha firmware, re-calibrated the docks and it sill persists.
The only new piece of information I have is that in my case I am using the XL with two tool heads. I have seen the issue at random on any of the tool heads, it is not isolated to a specific one.

**Comment by RuudGosens** [comment]
I just noticed that the tool-head I've changed the filament in makes a slight sideways movement on the x-axis before reaching its printing position the first time it's used after the filament change.

After printing its first layer, that tool-head crashes when it tries to dock.
In my case the crash only occurs with a tool-head that has had its filament changed.
The crash message then appears on my screen. I then manually resolve the crash. 
Then, follow the on-screen instructions, and the printer can be used normally again until the next filament change.
Only the tool-head where the filament was changed crashes after its first layer. The other tool-heads don't and dock normally in my case.
In my opinion is the cause of the problem the changes that are made that i read in the section:
 Lazier homing, more cautious calibration

Homing behavior on the XL and CORE One has been refined to avoid unnecessary movements. In cases such as filament load or unload, the printer now performs only basic homing, skipping the extra diagonal movements.

Maybe the skipping of the extra diagonal movements is a bit to much skipping in this case.

**Comment by fogarasia** [comment]
Same problem with my XL, mostly at the end of the print parking the tool.

**Comment by RuudGosens** [comment]
For now i went back to firmware 6.2.6 and wait with the next firmware update till the docking problems are solved.
I think my Prusa XL 5 head printer has had enough docking crashes for now.:)

**Comment by polarvogel** [comment]
Same for me, also see Prusa forum, many more XL users with issues

- missing steps
- 500€ toolheads crashing into the frame or carriage crashing into the toolheads
- extreme motor sounds
- failing calibrations with wrong instructions or extremely bad results (input sphaper calibration, phase stepping calibration)

The best case is, it just crashes after the print with no harm done, second best case is _just_ a failed print but worst case is hardware damage to the toolheads.

This firmware is a danger and should absolutely be pulled off the releases for XL users.

**Comment by tg73** [comment]
Same for me, parking at the end of the print.

**Comment by Chase-Money** [comment]
I also experienced this problem during filament changes with my primary 5TH XL running the alpha firmware this week. Finished the print, started a new one, kept happening. Resliced the file, still happened. It was giving me dock crashes and layer shifts as if something was making it skip steps or lose home position somehow? I got that impression at least.

Did a hard reboot of the printer by power cycling it with the switch. Stopped happening all together and hasn't returned so far. All single toolhead prints had done great most of the week, but multi toolhead prints began making this error occur all up till I rebooted the printer. Which I had not done after updating. I tend to just leave it on 24/7 honestly.

Wanted to add my experience in hopes it helps somehow. Happy to add crash logs if they would help.

Edit: this did not occur immediately in my case. My first week and a half of printing went great both single toolhead wise AND multi toolhead wise. The first crash occurred almost two weeks after updating, at the end of a print. Then started in at every tool change.

**Comment by Chase-Money** [comment]
> In my opinion is the cause of the problem the changes that are made that i read in the section:
>  Lazier homing, more cautious calibration
> 
> Homing behavior on the XL and CORE One has been refined to avoid unnecessary movements. In cases such as filament load or unload, the printer now performs only basic homing, skipping the extra diagonal movements.
> 
> Maybe the skipping of the extra diagonal movements is a bit to much skipping in this case.

I concur, not that it counts for anything. But I specifically found myself thinking "it's losing its home position on my support material tool head somehow." Then checked the firmware notes to find the addition of "lazier homing" and immediately went "I KNEW IT!"

**Comment by Timlindz** [comment]
Same for me, parking at the end of the print.

**Comment by 3d-gussner** [comment]
This should be solved in the next firmware release. Thanks for testing the alpha firmware.

**Comment by raphhorn** [comment]
it crashes at the start of the print everytime it try to pick the first tool and crashes if i stop the print and restart it works fine
i tried it on all toolheads same problem

**Comment by Adam8234** [comment]
This should be pulled from the alpha firmware list. XY motors skip during initial filament purging and crashes every time. Not a safe firmware to use on your XL. I get that it's alpha, but since this is a known issue, it should be pulled or at least stated in the release notes.

**Comment by DoubleStrike** [comment]
@3d-gussner is there any timeline for when we may see the next alpha/beta/rc/something for the XL? The last firmware was 7 weeks ago and, while it may not be true, it feels like the Core One owners are getting priority over us XL owners sometimes.

**Comment by 3d-gussner** [comment]
@DoubleStrike The new firmware release 6.4.0 and newer will combine one firmware for all printers. This makes it easier for the customers and support.

Testing all printers (different motion systems, motors, etc, and add-ons) take a while and a fix for a specific printer may (shouldn't but can) cause issues on others.

>it feels like the Core One owners are getting priority over us XL owners sometimes.

It is "normal" that a new printer gets more bug, enhancement and feature requests, so the pure amount of new tickets sometimes changes the priority.

The new tool collaboration to print "fluids" shows that the XL gets attention and new ideas are welcome.

I can't give a timeline or an estimate when the firmware will be released. But I can say that the testing of the new firmware is ongoing and issues that have been found are addressed very quickly by the developers.

These tests are very detailed and take some time. Sometimes we can get a partial test of one fix but sometimes the whole test has to be rerun.


Please remember that an alpha firmware may cause new issues and frankly this one has one, so please only use Alpha and Beta firmware's when you want to test it and don't expect it to work like a release candidate or final version.

We really appreciate that so many community XL members have been testing and reporting back issues and positive results. 🤗

**Comment by j28CLY** [comment]
I saw dock crashing today, while trying 6.4.0-alpha for the first time: I stopped a job that was printing with head#2, after which it moved, still holding head#2, to the normal idle position in the back-left corner of the printer. I then went into Phase Stepping in the Settings menu and tried to do the calibration there.
The printer immediately crashed head#2 into the parked head#1 multiple times, as if the printer was attempting to home itself in the back-left corner. Like it wasn't just barely grazing head#1, it was full-on ramming into it. I pressed Reset to stop it.

**Comment by murk-sy** [comment]
This issue should be resolved as of [6.4.0-RC2](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.4.0-RC2)

**Comment by dav991** [comment]
Can confirm that I didn't see the issue since updating to 6.4.0-rc2.

**Comment by metikumi** [comment]
I did several prints using the 6.4.0-rc2 and are now updating to 6.4.0. I had no head-crash issues. Head alignment with multiple heads is fine too.

**Comment by Kingkuul** [comment]
I've just updated my XL to 6.4  and its still having head crashing  issues i had to downgrade to 6.2.6
