### ISSUE TITLE
[BUG] Resume print after Powerloss not working

### ISSUE THREAD

**Issue by nicolai-wachenschwan** [prusa3d/Prusa-Firmware-Buddy#4944]
### Printer model

XL 5 head

### Firmware version

6.4.0-alpha

### Upgrades and modifications

High Flow Hotends

### Printing from...

USB drive

### Describe the bug

the printer was loosing steps (layershift), just starting to make a mess. Since I cannot pause and auto-home via the menue I did a powercycle, hoping the resume would trigger a homing and therefore recover the 500g print.

It did not. This was a feature working well in previous iterations. The current situation leaves me with 2 options:
A) use the buggy alpha
B) accept layershifts on almost all of my prints. (I checked the mechanical Kinematics)

### How to reproduce

print, power out, power on

### Expected behavior

A) not loose steps
B) resume print after power outage
C) option to manually trigger a homing via menue

**Comment by 3d-gussner** [comment]
@nicolai-wachenschwan Thanks for reporting. The alpha firmware shouldn't be used in production if you aren't ready to get failed prints.

Nevertheless, how did you perform the power panic? Turning off the printer with the switch will NOT trigger power panic. You need to pull the power plug.

> A) not loose steps

There is already a ticket and a solution in the development build. With the next firmware release this should be solved.

> B) resume print after power outage

How did you perform the power panic? Turning off the printer with the switch will NOT trigger power panic. You need to pull the power plug.

> C) option to manually trigger a homing via menue

There is also another ticket that requests this function.

**Comment by nicolai-wachenschwan** [comment]
@3d-gussner thanks for the quick response! I worked the week on pinning down the issue. 
Extruder 3 was not affected by layershifts (until now)
I now tried Both power down options, Both did Not work. 
Also we still get layershifts on a regular basis. Still working on crossing all possible Hardware influences of the List. 
My Team and i use this Printer at work and rely on the reliability of the machine to pump out Parts at a decent quality Level. thats why we bought a prusa after i suggested that. Not having it fully operational for weeks would cost us more money than a new Printer :/

BTW: the prusa link Surface does not work in the Alpha

**Comment by 3d-gussner** [comment]
@nicolai-wachenschwan Please try FW 6.4.0-RC2 or go back to the last stable firmware.
The alpha is an early stage firmware release and should only be used to test and not printing in production as things may go wrong.
