### ISSUE TITLE
[BUG]Prusa XL: Whenna print is stopped nextruder positioning goes haywire

### ISSUE THREAD

**Issue by bryn51** [prusa3d/Prusa-Firmware-Buddy#4965]
### Printer model

XL Multitool

### Firmware version

6.2.6

### Upgrades and modifications

None

### Printing from...

Prusa Connect

### Describe the bug

When stop button on LCD is tapped during a print, the extruder goes to a position just in front of Tool 1.
When a little later you want to park the tool, the printer tries to home but makes a complete mess of it. It has lost currency of its position.  If Control>Autohome is pressed, it similarly bisbehaves. Tool head crashes on the side of the printer, and similar incorrect movements.Also if it's tool 2, it may crash into the back of tool 1 which is docked.

### How to reproduce

Commence a print.
Wait a while until print has started extrusion.
Tap 'stop button'
Take note where the extruder moves to.
On control menu execute 'park current tool' and observe behaviour.
On control menu execute 'auto home' and observe behaviour.

Some like to argue if a report is a bug or an enhancement, but in this case I cannot beleive he behaviour observed is intentional by design.

### Expected behavior

Several extruder movements are plausible and could be deemed 'correct behaviour' when stop button is executed:
a) (most likely correct)> Park the current tool into its correct position in the tool changer.
b) (2nd choice) > Move extruder with tool to home position.

The reason (b) might be deemed plausible is that Prusa might want the user to be presented the opportunity to clean the nozzle or unload the filament. But I think this idea can be negated, as what the user really needs to do when a print is stopped is to clean the bed, and the extruder is best out of the way when that is done, and thus the best place to put the Tool is back in the tool changer.

I have seen this event to occur on multiple prints, and it happens *every time* the print is stopped. It should be easy to reproduce.

### Files

no crash dump occurs.

**Comment by Ro3Deee** [comment]
@bryn51  could you add a title for this bug?

**Comment by 3d-gussner** [comment]
@bryn51 This should be solved in 6.4.0-RC2

**Comment by bryn51** [comment]
Thats interesting.  

I am not keen on running  RC formare in my production environment, as  my business entirely relies upon functining equipment.

 I normally do not even look at using development versions, as my own development experience tells me they are still not 'finished' and as a commercial operator, I do not have the time to go about properly testing firmwaresoftware, that isn't my business.
I'm willing to look at it if I can have a version that has ONLY that issue solved in it, and not other enhancements and fixes that might cloud the issue. I've been there done that in terms of software development myself, and I'm no longer in that game (too old). And I know a lot about testing (to IBM standards) , most particularly how much work there is in fully testing it, and its essential to have a Full Functional specification before you start. I do not have that.

So maybe I just gotta wait until that 6.4.0 gets to nctual Release stage.

**Comment by Gik-0101** [comment]
I think this is also a duplicate.

Same as #4845 ?
